import "./globals.css";
import { Inter, Roboto_Mono } from "next/font/google";
import { ClientOnlyTopLoader } from "@/components/ClientOnlyTopLoader";
import { PrimeReactProvider } from "primereact/api";
import { AuthProvider } from "@/components/AuthContext";

const inter = Inter({ subsets: ["latin"] });

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});

export const metadata = {
  title: "Sistem Manajemen Sumber Daya Manusia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <PrimeReactProvider>
          <ClientOnlyTopLoader />
          <body className={`${inter.className} ${robotoMono.variable}`}>
            {children}
          </body>
        </PrimeReactProvider>
      </AuthProvider>
    </html>
  );
}
