// import "primereact/resources/primereact.min.css";
// import "primeicons/primeicons.css";
// import "primereact/resources/themes/lara-light-indigo/theme.css";
// import "primeflex/primeflex.css";

import "./globals.css";
import { Inter } from "next/font/google";
import { ClientOnlyTopLoader } from "@/components/ClientOnlyTopLoader";
import { PrimeReactProvider } from "primereact/api";
import { AuthProvider } from "@/components/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Sistem Manajemen Sumber Daya Manusia",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<AuthProvider>
				<PrimeReactProvider>
					<ClientOnlyTopLoader />
					<body className={inter.className}>{children}</body>
				</PrimeReactProvider>
			</AuthProvider>
		</html>
	);
}
